Buildering/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Buildering.Data.Models.Domain;
using Buildering.Data.Models.Repository;
using Buildering.Services.IService;
using Buildering.Services.Service;
using BuilderingApp.Models;

namespace Buildering.Controllers
{
    public class CommentController : Controller
    {
        ICommentService commentService;
        IRouteService routeService;
        public CommentController()
        {
            commentService = new CommentService();
            routeService = new RouteService();
        }

        //Get: Add Comment
        [Authorize]
        [HttpGet]
        public ActionResult AddCommentToRoute(int routeId)
        {
            return View();
        }

        //Post: Add Comment
        [HttpPost]
        public ActionResult AddCommentToRoute(Comment comment, int routeId)
        {
            {
                try
                {
                    commentService.AddCommentToRoute(comment, routeId);
                    return RedirectToAction("GetRoute", "Route", new { id = routeId });
                }
                catch
                {
                    return View();
                }
            }

        }
        //Get : Comment (To display details)
        public ActionResult GetComment(int id)
        {
            return View(commentService.GetComment(id));
        }

        //Get: Comments on Route page
        public ActionResult GetComments(int id)
        {
            return View(commentService.GetComments(id));
        }

        //Get: Edit Comment
        [Authorize]
        [HttpGet]
        public ActionResult EditComment(int id)
        {
            Comment comment = new Comment();
            //Getting comment
            comment = commentService.GetComment(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("Admin") && comment.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who added this comment to edit it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = comment.RouteId;
                return View();
            }
            //Displaying comment
            return View(comment);
        }
        //Post: Edit Comment
        [HttpPost]
        public ActionResult EditComment(Comment comment/*, int id*/)
        {
            {
                try
                {
                    commentService.EditComment(comment/*, id*/);
                    return RedirectToAction("GetRoute", "Route", new { ID = comment.RouteId });
                }

                catch
                {
                    return View();
                }
            }
        }

        //Get: Delete Comment
        [Authorize]
        [HttpGet]
        public ActionResult DeleteComment(int id)
        {
            Comment comment = new Comment();
            //Getting comment
            comment = commentService.GetComment(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("Admin") && comment.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who added this comment to delete it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = comment.RouteId;
                return View();
            }
            //Displaying comment
            return View(comment);
        }

        //Post: Delete Comment
        [HttpPost]
        public ActionResult DeleteComment(int routeId, int commentId)
        {
            {
                try
                {
                    //Deleting the comment
                    commentService.DeleteComment(commentId);
                    //Navigating back to the Route with the var routeID
                    return RedirectToAction("GetRoute", "Route", new { ID = routeId });
                }
                catch
                {
                    return View();
                }
            }
        }
    }
}

Buildering/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Buildering.Data.Models.Domain;
using Buildering.Data.Models.Repository;
using Buildering.Services.IService;
using Buildering.Services.Service;
using BuilderingApp.Models;

namespace Buildering.Controllers
{
    public class PhotoController : Controller
    {
        IPhotoService photoService;
        IRouteService routeService;
        public PhotoController()
        {
            photoService = new PhotoService();
            routeService = new RouteService();
        }
        
        //Get: Add Photo within Route
        [Authorize]
        [HttpGet]
        public ActionResult AddPhotoToRoute(int routeId)
        {
            return View();
        }
        //Post: Add Photo within Route
        [HttpPost]
        public ActionResult AddPhotoToRoute(Photo photo, int routeId)
        {
            try
            {
                photoService.AddPhotoToRoute(photo, routeId);
                return RedirectToAction("GetRoute", "Route", new { id = routeId });
            }
            catch
            {
                return View();
            }
        }

        //Get : Photo (To display details)
        public ActionResult GetPhoto(int id)
        {
            return View(photoService.GetPhoto(id));
        }

        //Get: Photos on Route page
        public ActionResult GetPhotos(int id)
        {
            Route route = new Route();
            route = routeService.GetRoute(id);
            IList<Photo> photo = route.Photos.ToList();
            return View(photo);
        }
        //Get: Delete Photo
        [Authorize]
        [HttpGet]
        public ActionResult DeletePhoto(int id)
        {
            Photo photo = new Photo();
            //Getting Photo
            photo = photoService.GetPhoto(id);
            //If photo not found
            if (photo == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("Admin") && photo.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who added this photo to delete it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = photo.RouteId;
                return View();
            }
            //Displaying Photo
            return View(photo);
        }

        //Post: Delete Photo
        [HttpPost]
        public ActionResult DeletePhoto(int routeId, int photoId)
        {
            {
                try
                {
                    //Deleting the photo
                    photoService.DeletePhoto(photoId);
                    //Navigating back to the Route with the var routeID
                    return RedirectToAction("GetRoute", "Route", new { ID = routeId });
                }
                catch
                {
                    return View();
                }
            }
        }

    }
}

Buildering/Controllers/RouteController.cs
using Buildering.Data.Models.Domain;
using Buildering.Services.IService;
using Buildering.Services.Service;
using BuilderingApp.Models;
using NUnit.Framework.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;//for contact action
using System.Net.Mail; // for navigating email
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Buildering.Controllers
{
    public class RouteController : Controller
    {
        IRouteService routeService;
        IUserService userService;
        public RouteController()
        {
            routeService = new RouteService();
            userService = new UserService();
        }
        //Get: Contact Admin Action
        [Authorize]
        [HttpGet]
        public ActionResult ContactAdmin(string returnUrl)
        {
            returnUrl = Request.UrlReferrer.AbsoluteUri;
            ViewData["URL"] = returnUrl;
            return View();
        }

        //Post: Contact Admin Action
        [HttpPost]
        public ActionResult ContactAdmin(string name, string subject, string message, 
            string returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    routeService.ContactAdmin(name, subject, message, returnUrl);
                    return RedirectToAction("GetRoutes", "Route");
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Some Error";
            }
            return View();
        }

        // GET: Route/Create
        [Authorize]
        [HttpGet]
        public ActionResult AddRoute(string Coordinate)
        {

            ViewBag.Coordinate = Coordinate;
            return View();

        }
        // POST: Route/Create
        [HttpPost]
        public ActionResult AddRoute(HttpPostedFileBase topo, Route route)
        {
            try
            {
                routeService.AddRoute(topo, route);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // Get: Route
        public ActionResult GetRoute(int id)
        {
            return View(routeService.GetRoute(id));
        }

        public ActionResult GetRoutes(Nullable<Buildering.Data.Models.Domain.Route.Grades> grading, string searchstring)
        {
            return View(routeService.SearchRoutes(grading, searchstring));
        }

        //Get: Edit Route
        public ActionResult EditRoute(int id)
        {
            Route route = new Route();
            route = routeService.GetRoute(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("Admin") && route.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who created this route to edit it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = id;
                return View(); 
            }
            return View(route);
        }
        //Post: Edit Route
        [HttpPost]
        public ActionResult EditRoute(HttpPostedFileBase topo, Route route/*, int id*/)
        {
            {
                try
                {
                    routeService.EditRoute(topo, route/*, id*/);
                    return RedirectToAction("GetRoute", "Route", new { id = route.ID });
                }

                catch
                {
                    return View();
                }
            }
        }
        //Get : Delete Route
        [Authorize]
        [HttpGet]
        public ActionResult DeleteRoute(int id)
        {
            Route route = new Route();
            //Getting route
            route = routeService.GetRoute(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            //Checks if user is an admin or the original uploader
            if (!User.IsInRole("Admin") && route.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who created this route to edit it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = id;
                return View();
            }
            return View(route);
        }

        //Post: Delete Route
        [HttpPost]
        public ActionResult DeleteRoute(Route route, int id)
        {
            {
                try
                {
                    //Deleting route
                    routeService.DeleteRoute(id);
                    return RedirectToAction("GetRoutes", "Route");
                }
                catch
                {
                    return View();
                }
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult VoteOnGrade(int ID)
        {
            return View(); // change to redirect to action 
        }

        [HttpPost]
        public ActionResult VoteOnGrade(int ID, Buildering.Data.Models.Domain.Route.Grades VotedGrade, string userName)
        {
            var result = routeService.VoteOnGrade(ID, (int)VotedGrade, userName);
            if (result)
            {
                return RedirectToAction("GetRoute", "Route", new { id = ID });
            }
            else
            {
                string errorMsg = "You have already voted on this route's grade";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = ID;
                return View();
            }
        }
    }
}

Buildering/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Buildering.Data.Models.Domain;
using Buildering.Data.Models.Repository;
using Buildering.Services.IService;
using Buildering.Services.Service;
using BuilderingApp.Models;

namespace Buildering.Controllers
{
    public class VideoController : Controller
    {
        IVideoService videoService;
        IRouteService routeService;

        public VideoController()
        {
            videoService = new VideoService();
            routeService = new RouteService();
        }

        //Get: Add Video within Route
        [Authorize]
        [HttpGet]
        public ActionResult AddVideoToRoute(int routeId)
        {
            return View();
        }
        //Post: Add Video within Route
        [HttpPost]
        public ActionResult AddVideoToRoute(Video video, int routeId)
        {
            {
                try
                {
                    videoService.AddVideoToRoute(video, routeId);
                    return RedirectToAction("GetRoute", "Route", new { id = routeId });
                }
                catch
                {
                    return View();
                }
            }

        }
        //Get : Video (To display details)
        public ActionResult GetVideo(int id)
        {
            return View(videoService.GetVideo(id));
        }

        //Get: Videos on Route page
        public ActionResult GetVideos(int id)
        {
            Route route = new Route();
            route = routeService.GetRoute(id);
            IList<Video> video = route.Videos.ToList();
            return View(video);
        }

        //Get: Delete Video
        [Authorize]
        [HttpGet]
        public ActionResult DeleteVideo(int id)
        {
            Video video = new Video();
            //Getting Video
            video = videoService.GetVideo(id);
            //If video not found
            if (video == null)
            {
                return HttpNotFound();
            }
            if (!User.IsInRole("Admin") && video.User != System.Web.HttpContext.Current.User.Identity.Name)
            {
                string errorMsg = "You must be the user who added this comment to edit it ";
                ViewBag.errorMsg = errorMsg;
                ViewBag.ID = video.RouteId;
                return View();
            }
            //Displaying video
            return View(video);
        }

        //Post: Delete Video
        [HttpPost]
        public ActionResult DeleteVideo(int routeId, int videoId)
        {
            {
                try
                {
                    //Deleting the video
                    videoService.DeleteVideo(videoId);
                    //Navigating back to the Route with the var routeID
                    return RedirectToAction("GetRoute", "Route", new { ID = routeId });
                }
                catch
                {
                    return View();
                }
            }
        }

    }
}

Buildering/Views/Route/AddRoute.cshtml
@model Buildering.Data.Models.Domain.Route

@{
    ViewBag.Title = "AddRoute";
}

<head>
    @*Including leaflet.js CSS file and Javascript file*@
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    <style>
        #mapid {
            height: 300px;
        }
    </style>
</head>

<h2>Add Route</h2>
@*mapid div is container for the map created using leaflet.js it must be declared before leaflet.js code populates it*@
<div id="mapid"></div>

<script>
    //Location for map start and marker taken from model coordinates
    var suppliedLoc = '@ViewBag.Coordinate';
    var coords = suppliedLoc.split(",");

    //Specifying map parameters: initial location, where to source the background map, level of zoom allowed
    var map = L.map('mapid').setView([coords[0], coords[1]], 19);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 20,
            maxNativeZoom: 19,
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

     //Marker is set at the coordinates the user input, it is draggable
     var marker = L.marker([coords[0], coords[1]], { draggable: 'true' }).addTo(map);

    //Marker is able to be dragged, when the drag finishes it updates the coordinates to be input
     marker.on('dragend', function (e) {
         coords = marker.getLatLng().lat + ',' + marker.getLatLng().lng;
         document.getElementById("Coordinate").value = coords;
     });

    //setting the coordinates to be input from incoming data
    function setInitialCoords() {
        document.getElementById("Coordinate").value = suppliedLoc;
    }

    window.onload = setInitialCoords;

    function GrOut(rating) {
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'far fa-star')
        }
    }
    function GrOver(rating) {
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'fas fa-star')
        }
    }
    function GrClick(rating) {
        $("#lblRating").val(rating);
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'fas fa-star');
        }
        for (var i = rating + 1; i <= 5; i++) {
            $("#span" + i).attr('class', 'far fa-star');
        }
    }
    function GrSelected() {
        var rating = $("#lblRating").val();
        for (var i = 1; i <= rating; i++) {
            $("#span" + i).attr('class', 'fas fa-star');
        }
    }
</script>


@using (Html.BeginForm("AddRoute", "Route", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Route</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <input class="form-control text-box single-line valid" id="Coordinate" name="Coordinate" type="hidden" value="@ViewBag.Coordinate" aria-invalid="false">

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Topo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" value="Upload" name="Topo" required />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <div onmouseout="GrSelected()">
                    <span id="span1" onmouseout="GrOut(1)" onmouseover="GrOver(1)" onclick="GrClick(1)" class="far fa-star" style="font-size:15px;color:yellow"></span>
                    <span id="span2" onmouseout="GrOut(2)" onmouseover="GrOver(2)" onclick="GrClick(2)" class="far fa-star" style="font-size:15px;color:yellow"></span>
                    <span id="span3" onmouseout="GrOut(3)" onmouseover="GrOver(3)" onclick="GrClick(3)" class="far fa-star" style="font-size:15px;color:yellow"></span>
                    <span id="span4" onmouseout="GrOut(4)" onmouseover="GrOver(4)" onclick="GrClick(4)" class="far fa-star" style="font-size:15px;color:yellow"></span>
                    <span id="span5" onmouseout="GrOut(5)" onmouseover="GrOver(5)" onclick="GrClick(5)" class="far fa-star" style="font-size:15px;color:yellow"></span>
                </div>
                <div>
                    <input type="hidden" name="Rating" id="lblRating" />
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(Model => Model.Grade,
            new SelectList(Enum.GetValues(typeof(Buildering.Data.Models.Domain.Route.Grades))),
            "Select Grade")
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>
        <input class="form-control text-box single-line valid" id="User" name="User" type="hidden" value="@System.Web.HttpContext.Current.User.Identity.Name" aria-invalid="false">

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Route" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <label class="label-success">@ViewBag.SuccessMessage</label>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Buildering/Views/Route/GetRoute.cshtml
@model Buildering.Data.Models.Domain.Route

@{
    ViewBag.Title = "GetRoute";
}
<head>
    @*Including leaflet.js CSS file and Javascript file*@
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin="" />

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin="">
    </script>

    <style>
        #mapid {
            height: 300px;
            position: relative;
        }

        @*@media used with display: block to show buttons only on mobile and display: none when not *@
        @@media only screen and (max-width: 768px) {
            button#goToGPS {
                position: absolute;
                z-index: 500;
                bottom: 30px;
                right: 20px;
                background: transparent;
                border: none !important;
                display: block;
            }

            i.fa-compass {
                z-index: 400;
                position: absolute;
                font-size: x-large;
                color: red;
                display: block;
            }

            button#goToCurrentRoute {
                position: absolute;
                z-index: 500;
                top: 10px;
                right: 15px;
                background: transparent;
                border: none !important;
                display: block;
            }

            i.fa-map-marker-alt {
                z-index: 400;
                position: absolute;
                font-size: x-large;
                color: red;
                display: block;
            }
        }

        #goToGPS{
            display: none;
        }

        .fa-compass{
            display: none;
        }

        #goToCurrentRoute{
            display: none;
        }

        .fa-map-marker-alt{
            display: none;
        }
    </style>
</head>

@*mapid div is container for the map created using leaflet.js it must be declared before leaflet.js code populates it*@

<div id="mapid">
    <button onclick="goToCurrentRoute()" id="goToCurrentRoute">
        <i class="fas fa-map-marker-alt"></i>
    </button>
    <button onclick="goToCurrentGPS()" id="goToGPS">
        <i class="far fa-compass"></i>
    </button>
</div>


<script>

    //Location for map start and marker taken from model coordinates
    var suppliedLoc = '@Model.Coordinate';
    var coords = suppliedLoc.split(",");

    //Specifying map parameters: initial location, where to source the background map, level of zoom allowed
    var map = L.map('mapid', { attributionControl: false }).setView([coords[0], coords[1]], 19);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 20,
            maxNativeZoom: 19,
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
    L.control.attribution({ position: 'bottomleft' }).addTo(map);
    var marker = L.marker([coords[0], coords[1]]).addTo(map);

    //GPS functionality, shows user on map when GPS enabled. userLocation must be specified first,
    //it is then altered every time location is found and removes the previous userLocation circle.
    var userLocation = L.circle([48.526, 123.236]).addTo(map);
    function onLocationFound(e) {
        var radius = e.accuracy / 2;
        userLocation.remove();
        userLocation = L.circle(e.latlng, radius, { color: 'red' }).addTo(map);
        userLocation.addTo(map);
    }
    map.on('locationfound', onLocationFound);
    map.locate({ setView: false, watch: true, enableHighAccuracy: true });

    //Functions to take user to their current location or back to the route location
    function goToCurrentGPS() {
        map.locate({ setView: true, watch: false, enableHighAccuracy: true });
    }
    function goToCurrentRoute() {
        map.flyTo([coords[0], coords[1]], 19);
    }

    //Toggle function to show or hide div containing videos
    function ShowVideos() {

        var videos = document.getElementById("videos");
        var videoButton = document.getElementById("videoButton");

        if (videos.style.display === "none") {
            videos.style.display = "block";
            videoButton.textContent = "Hide Videos";
        } else {
            videos.style.display = "none";
            videoButton.textContent = "Show Videos";
        }
    }

</script>
<h2>@Model.Name</h2>

<div>

    <hr />

    @if (ViewContext.HttpContext.User.IsInRole("Admin") || ViewContext.HttpContext.User.Identity.Name == Model.User)
    {
        <ul>
            <li>@Html.ActionLink("Edit", "EditRoute", new { id = Model.ID })</li>
            <li>@Html.ActionLink("Delete", "DeleteRoute", new { id = Model.ID })</li>
        </ul>
    }

    <dl class="dl-horizontal">
        <dd>
            @if (Model.Topo != "")
            {
                <img src="@Url.Content("~/ImageFolder/" + Model.TopoName)" alt="File not found" height="250" width="250" />
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @for (int i = 0; i < Model.Rating; i++)
            {
                <span class="fas fa-star" style="font-size:15px;color:yellow"></span>
            }
            @for (int i = Model.Rating; i < 5; i++)
            {
                <span class="far fa-star" style="font-size:15px;color:wheat"></span>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VotedGrade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VotedGrade)
        </dd>
        @Html.ActionLink("Vote on Grade", "VoteOnGrade", new { ID = Model.ID })
    </dl>
</div>

<p style="text-align:right;">
    @Html.ActionLink("Report route", "ContactAdmin")
</p>
<p>
    <h2>Comments of @Model.Name </h2>
</p>

@if (Model.Comments.Count != 0)
{
    @Html.Partial("~/Views/Comment/GetComments.cshtml", Model.Comments);
}
@Html.ActionLink("Add Comment", "AddCommentToRoute", "Comment", new { routeId = Model.ID }, null)
<p>
    <h2>Photos of @Model.Name </h2>
</p>
@if (Model.Photos.Count != 0)
{
    @Html.Partial("~/Views/Photo/GetPhotos.cshtml", Model.Photos);
}
@Html.ActionLink("Add Photo", "AddPhotoToRoute", "Photo", new { routeId = Model.ID }, null)

<p>
    <h2>Videos of @Model.Name </h2>
</p>
<button onclick="ShowVideos()" id="videoButton">Show Videos</button>
<div id="videos" style="display:none">
    @if (Model.Videos.Count != 0)
    {
        @Html.Partial("~/Views/Video/GetVideos.cshtml", Model.Videos);
    }
    @Html.ActionLink("Add Video", "AddVideoToRoute", "Video", new { routeId = Model.ID }, null)
</div>